#!/usr/bin/env python
__all__ = ['copycat']
from CopyCat import CopyCat
import sys
import select

def has_stdin():
    return select.select([sys.stdin,],[],[],0.0)[0]


def clip_copy(name, value=None):
    if not value and has_stdin():
        value = sys.stdin.read()

    assert value, 'not copy value'

    CopyCat().copy(value, name)


def clip_paste(name=None):
    print CopyCat().paste(name)


def copycat(value=None, name=None, paste=False):
    '''
    option:
    -p, --paste
    -n=<str>, --name=<str>
    '''
    if paste:
        return clip_paste(name)
    else:
        return clip_copy(name, value)


import clime.now
